### PR TITLE
Always apply parameter files

### LINKED ISSUE #16: parameters are not loaded during diff, making it misleading/useless
as a workaround we are using `update  --plan-only` but it's kinda weird that it did not work ...

### PR DESCRIPTION
**Pull request by chrisroberts**
Fixes #16

### CODE REVIEW

File: lib/sfn-parameters/stacks.rb [hunk 1]
```diff
@@ -10,17 +10,16 @@ class ParametersStacks < ParametersInfrastructure
...
-        root_path = config.fetch(:sfn_parameters, :directory, 'stacks')
-        paths = Dir.glob(File.join(root_path, "#{stack_name}{#{VALID_EXTENSIONS.join(',')}}")).map(&:to_s)
-        if(paths.size > 1)
-          raise ArgumentError.new "Multiple parameter file matches encountered! (#{paths.join(', ')})"
-        elsif(paths.empty?)
+        root_path = config.fetch(:sfn_parameters, :directory, "stacks")
+        paths = Dir.glob(File.join(root_path, "#{stack_name}{#{VALID_EXTENSIONS.join(",")}}")).map(&:to_s)
+        if paths.size > 1
+          raise ArgumentError.new "Multiple parameter file matches encountered! (#{paths.join(", ")})"
+        elsif (paths.empty?)
```
Comment (grosser) [inline lib/sfn-parameters/stacks.rb]: kinda inconsistent to use regular no param style for if and params for the elsif

**Comment by grosser** [comment]
hard to see what's going on when mixing style changes with behavior changes
